name: fudeo_tales
description: "A demo project to showcase in app purchases"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  pine: ^1.0.3
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/divider.png
    - assets/fudeo.png
    - assets/purchases.png
    - assets/stories.json
    - assets/subscribe.png
    - assets/stories/brave_girl.jpeg
    - assets/stories/curious_kitty.jpeg
    - assets/stories/curious_penguin.jpeg
    - assets/stories/cute_fairy.jpeg
    - assets/stories/enchanted_garden.jpeg
    - assets/stories/little_dragoon.jpeg
    - assets/stories/mouse_with_candies.jpeg
    - assets/stories/rainbowed_kitty.jpeg
    - assets/stories/singing_whale.jpeg
    - assets/stories/smiling_princess.jpeg